<?php

return [
    'AR' => 'Argentina',
    'AU' => 'Australia',
    'BR' => 'Brasil',
    'CA' => 'Canadá',
    'CN' => 'China',
    'CO' => 'Colombia',
    'KR' => 'Corea del Sur',
    'ES' => 'España',
    'US' => 'Estados Unidos',
    'FR' => 'Francia',
    'DE' => 'Alemania',
    'GR' => 'Grecia',
    'IN' => 'India',
    'ID' => 'Indonesia',
    'IR' => 'Irán',
    'IQ' => 'Irak',
    'IT' => 'Italia',
    'JP' => 'Japón',
    'MX' => 'México',
    'NG' => 'Nigeria',
    'PK' => 'Pakistán',
    'PE' => 'Perú',
    'GB' => 'Reino Unido',
    'RU' => 'Rusia',
    'ZA' => 'Sudáfrica',
    'SE' => 'Suecia',
    'CH' => 'Suiza',
    'TR' => 'Turquía',
    'UA' => 'Ucrania',
    'VE' => 'Venezuela',
];